function write_hypergraph_csv_file(X_N_tc, X_S_tc, subj_N, subj_S)

file_names = {  'data/hypergraphN10.csv',...
    'data/hypergraphN9.csv',...
    'data/hypergraphN8.csv',...
    'data/hypergraphN7.csv',...
    'data/hypergraphN6.csv',...
    'data/hypergraphN5.csv',...
    'data/hypergraphN4.csv',...
    'data/hypergraphN3.csv',...
    'data/hypergraphN2.csv',...
    'data/hypergraphN1.csv',...
    'data/hypergraphN0.csv',...
    'data/hypergraphN-1.csv',...
    'data/hypergraphN-2.csv',...
    'data/hypergraphN-3.csv',...
    'data/hypergraphN-4.csv',...
    'data/hypergraphN-5.csv'};

for file_name_ind = 1:size(file_names,2)
    file_name = file_names{file_name_ind};
    fid = fopen(file_name,'w');
    c = 1;
    for j = 1:size(X_N_tc,1)
        for k = 1:size(X_N_tc,2)
            for i = 1:size(X_N_tc,3)
                if abs(X_N_tc(j,k,i,subj_N))> 2^(11-file_name_ind)
                    fprintf(fid,'%d, %d, %d, %d\n',c,j,k,i);
                end
                c = c + 1;
            end
        end
    end
    fclose(fid);
end

file_names = {  'data/hypergraphS10.csv',...
    'data/hypergraphS9.csv',...
    'data/hypergraphS8.csv',...
    'data/hypergraphS7.csv',...
    'data/hypergraphS6.csv',...
    'data/hypergraphS5.csv',...
    'data/hypergraphS4.csv',...
    'data/hypergraphS3.csv',...
    'data/hypergraphS2.csv',...
    'data/hypergraphS1.csv',...
    'data/hypergraphS0.csv',...
    'data/hypergraphS-1.csv',...
    'data/hypergraphS-2.csv',...
    'data/hypergraphS-3.csv',...
    'data/hypergraphS-4.csv',...
    'data/hypergraphS-5.csv'};

for file_name_ind = 1:size(file_names,2)
    file_name = file_names{file_name_ind};
    fid = fopen(file_name,'w');
    c = 1;
    for j = 1:size(X_S_tc,1)
        for k = 1:size(X_S_tc,2)
            for i = 1:size(X_S_tc,3)
                if abs(X_S_tc(j,k,i,subj_S))> 2^(11-file_name_ind)
                    fprintf(fid,'%d, %d, %d, %d\n',c,j,k,i);
                end
                c = c + 1;
            end
        end
    end
    fclose(fid);
end

